config/routes.rb
Rails.application.routes.draw do
  resources :autos
  
  root to: "autos#home" 
  

end

app/models/auto.rb
class Auto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :set_auto, only: [:show, :edit, :update, :destroy]

def home
  
end


  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.all
  end

  # GET /autos/1
  # GET /autos/1.json
  def show
  end

  # GET /autos/new
  def new
    @auto = Auto.new
  end

  # GET /autos/1/edit
  def edit
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(auto_params)

    respond_to do |format|
      if @auto.save
        format.html { redirect_to @auto, notice: 'Auto was successfully created.' }
        format.json { render :show, status: :created, location: @auto }
      else
        format.html { render :new }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autos/1
  # PATCH/PUT /autos/1.json
  def update
    respond_to do |format|
      if @auto.update(auto_params)
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto }
      else
        format.html { render :edit }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto.destroy
    respond_to do |format|
      format.html { redirect_to autos_url, notice: 'Auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto
      @auto = Auto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_params
      params.require(:auto).permit(:name, :modelo, :year, :color, :precio, :img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/views/autos/_form.html.erb
<%= form_for(@auto) do |f| %>
  <% if @auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auto.errors.count, "error") %> prohibited this auto from being saved:</h2>

      <ul>
      <% @auto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
   <div class="field">
    <%= f.label :img %><br>
    <%= f.text_field :img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/autos/edit.html.erb
<h1>Editing Auto</h1>

<%= render 'form' %>

<%= link_to 'Show', @auto %> |
<%= link_to 'Back', autos_path %>

app/views/autos/home.html.erb
<div class="jumbotron">
    <center>
        <h1>Welcome to Pancho's car shop</h1>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhpbZivO2fyMigPlwhRW2KsVTjMzAzRxWMvQ7txq5fWxsNaz4y" alt="pancho's car shop" width=500px>
        <br>
        <%= link_to "Check out our cars", autos_path, class: "btn btn-default"%>
    </center>
    
</div>

app/views/autos/index.html.erb
<h1>Pancho's cars</h1>
<div class="row">
  <% @autos.each do |auto| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= auto.img %>" alt="pancho's cars">
      <div class="caption">
        <h3><%= auto.name %></h3>
        <h3>Cost: <%= auto.precio %></h3>
        <%= link_to "More info", auto, class: "btn btn-default" %>
        
      </div>
    </div>
    
  </div>
  <% end %>
</div>

<br>

<%= link_to "New car", new_auto_path, class: "btn btn-default" %>

app/views/autos/new.html.erb
<h1>New Auto</h1>

<%= render 'form' %>

<%= link_to 'Back', autos_path %>

app/views/autos/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <center>
    <h1><%= @auto.name %></h1>
    <img src="<%= @auto.img %>" alt="Pancho's car" width=500px>
  </center>
  <h3>Marca: <%= @auto.name %></h3>
  <h3>Modelo: <%= @auto.modelo %></h3>
  <h3>Year: <%= @auto.year %></h3>
  <h3>Precio: <%= @auto.precio %></h3>
</div>




<%= link_to 'Edit', edit_auto_path(@auto) %> |
<%= link_to 'Back', autos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Workspace</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/united/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Autos", autos_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>